src/Entity/Booking.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date d'arrivée doit être au bon format!")
     * @Assert\GreaterThan(
     *      "today", 
     *      message="La date d'arrivée doit être ultérieur à la date d'aujourd'hui")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date de départ doit être au bon format!")
     * @Assert\GreaterThan(
     *      propertyPath="startDate", 
     *      message="La date de départ doit être plus éloignée que la date d'arrivée")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * Callback function called before flushing the booking
     *
     * @ORM\PrePersist
     * 
     * @return void
     */
    public function prePersist() {
        if(empty($this->createdAt)) {
            $this->createdAt = new DateTime();
        }
        if(empty($this->amount)) {
            // price of the ad * number of days
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function isBookableDates() {
        // First, we need to know the unavailable dates of the Ad
        $notAvailableDays = $this->ad->getNotAvailableDays();
        // Then, we need to compare the selected dates with the unavailable ones
        $bookingDays = $this->getDays();

        $formatDay = function($day) {
            return $day->format('Y-m-d');        
        };

        // Array that contains days as string
        $days         = array_map($formatDay, $bookingDays);
        $notAvailable = array_map($formatDay, $notAvailableDays);

        foreach($days as $day) {
            if(array_search($day, $notAvailable) !== false) return false;
        }

        return true;
    }

    /**
     * Return an array that contains booking's days
     *
     * @return array Object array DateTime that represents the days of the booking
     */
    public function getDays() {
        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );
        
        $days = array_map(function($dayTimeStamp) {
            return new \DateTime(date('Y-m-d', $dayTimeStamp));
        }, $resultat);

        return $days;
    }

    public function getDuration() {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ApplicationType
{
    private $transformer;

    public function __construct(FrenchToDateTimeTransformer $transformer) {
        $this->transformer = $transformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'startDate', 
                TextType::class, 
                $this->getConfiguration("Date d'arrivée", "Indiquez la date de votre arrivée"))
            ->add(
                'endDate', 
                TextType::class, 
                $this->getConfiguration("Date de départ", "Indiquez la date de départ"))
            ->add(
                'comment', TextareaType::class,
                $this->getConfiguration(
                    false, 
                    "Si vous avez un commentaire, n'hésitez pas à en faire part !",
                    [
                        "required" => false
                    ]))
        ;

        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Monolog\Handler\HandlerWrapper;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * 
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad, Request $request, EntityManagerInterface $manager)
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            $booking->setBooker($user)
                    ->setAd($ad);

            // If selected days are not available
            if(!$booking->isBookableDates()) {
                $this->addFlash(
                    'warning',
                    "Les dates que vous avez choisies ne peuvent être réservées :
                    elles sont déjà prises."
                );
            } else {
                // Else, we register and redirect
                $manager->persist($booking);
                $manager->flush();
                
                return $this->redirectToRoute("booking_show", 
                [
                    "id" => $booking->getId(),
                    "withAlert" => true
                ]);
            }
            
        }

        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * Display a booking page
     *
     * @Route("/booking/{id}/", name="booking_show")
     * 
     * @param Request $request
     * @param Booking $booking
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function show(Booking $booking, Request $request, EntityManagerInterface $manager) {
        
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {            
            $comment->setAd($booking->getAd())
                    ->setAuthor($this->getUser());

            $manager->persist($comment);
            $manager->flush();

            $this->addFlash(
                'success',
                "Votre commentaire a bien été pris en compte"
            );
        }

        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce {{ ad.title }} {% endblock %}

{% block stylesheets %}

    <link rel="stylesheet" 
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.
    0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" 
    crossorigin="anonymous" />

{% endblock %}

{% block body %}

    <div class="container">
        <h1>Réservez pour l'annonce : <em>{{ ad.title }}</em></h1>
        <p>Vous êtes sur le point de réserver le bien de <strong>{{ ad.author.fullname }}
        </strong>, dites nous tout, on s'occupe du reste !</p>

        {{ form_start(form) }}

        <div class="alert alert-info">
            <h4>Commencez par nous dire quelles sont les dates qui vous intéressent !</h4>
            <div class="row">
                <div class="col">
                    {{ form_row(form.startDate) }}
                </div>
                <div class="col">
                    {{ form_row(form.endDate) }}
                </div>
            </div>
            <h4 class="mt-2">Montant du séjour : <span id="amount">...</span> &#8364;</h4>
            <span id="days">0</span> nuit(s) à {{ ad.price | number_format(2, ',', ' ') }}&#8364; par nuit

            <h4 class="mt-3">Vous avez un commentaire ?</h4>
            {{ form_row(form.comment) }}
        </div>


        <h2>Vous avez terminé !</h2>
        <p>Vacances de rêves ? Hébergement pour le boulot ? Peu importe, on est avec vous !</p>

        <button type="submit" class="btn btn-success">Je réserve !</button>
        {{ form_end(form) }}
    </div>

{% endblock %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" 
    integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" 
    crossorigin="anonymous"></script>

    <script>
        $(document).ready(function() {
            $('#booking_startDate, #booking_endDate').datepicker({
                format: 'dd/mm/yyyy',
                datesDisabled: [
                    {% for day in ad.notAvailableDays %}
                        "{{ day.format('d-m-Y') }}",
                    {% endfor %}
                ],
                startDate: new Date()
            });
            $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
        });

        function calculateAmount() {
            // Get dates
            const endDate = new Date(
                $('#booking_endDate')
                    .val()
                    .replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1')
            );

            const startDate = new Date(
                $('#booking_startDate')
                    .val()
                    .replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1')
            );

            if(startDate && endDate && startDate < endDate) {
                // Milliseconds contained in a single day
                const DAY_TIME  = 24 * 60 * 60 * 1000;

                const interval  = endDate.getTime() - startDate.getTime();
                const days      = interval / DAY_TIME;
                const amount    = days * {{ ad.price }};

                $('#days').text(days);
                $('#amount').text(amount.toLocaleString('fr-FR'));
            }
        }
    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation n° {{ booking.id }}{% endblock %}

{% block body %}
    {% set ad = booking.ad %}
    {% set author = ad.author %}
    <div class="container">
        <h1 class="my-5">Votre réservation (n°{{ booking.id }}) </h1>

        {% if app.request.query.get('withAlert') %}

            <div class="alert alert-success">
                <h4 class="alert-heading">Bravo !</h4>
                <p>
                    Votre réservation auprès de
                    <strong>
                        <a href="{{ path('user_show', {'slug' : author.slug}) }}">{{ author.fullname}}</a>
                    </strong>
                    pour l'annonce
                    <strong>
                        <a href="{{ path('ads_show', {'slug': ad.slug }) }}">{{ ad.title }}</a>
                    </strong>
                    a bien été prise en compte !
                </p>
            </div>

        {% endif %}

        <div class="row">
            <div class="col">
                <div class="alert alert-dark">
                    <h2>Détails</h2>
                    <dl class="row">
                        <dt class="col-md-4">Numéro</dt>
                        <dd class="col-md-8">{{ booking.id }}</dd>
                        <dt class="col-md-4">Date d'arrivée</dt>
                        <dd class="col-md-8">{{ booking.startDate | date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Date de départ</dt>
                        <dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
                        <dt class="col-md-4">Nombre de nuits</dt>
                        <dd class="col-md-8">{{ booking.duration }}</dd>
                        <dt class="col-md-4">Montant total</dt>
                        <dd class="col-md-8">{{ booking.amount | number_format(2, ',', ' ') }} &#8364;</dd>
                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{ booking.comment | default('Aucun commentaire') }}</dd>
                    </dl>

                    <hr>

                    <h2 class="alert-heading">Votre hôte</h2>
                    <div class="row mb-3">
                        <div class="col-3">
                            <img src="{{author.picture}}" class="avatar avatar-medium" alt="Avatar de {{author.fullname}}">
                        </div>
                        <div class="col-9">
                            <h4>
                                <a href="{{ path('user_show', {'slug' : author.slug }) }}">{{ author.fullname }}</a>
                            </h4>

                            <span class="badge badge-primary">{{ author.ads | length }} annonces</span>
                        </div>
                    </div>
                    {{ author.description | raw }}

                    <a href="{{ path('user_show', {'slug': author.slug }) }}" class="btn btn-primary">Plus d'infos sur {{ author.firstName }}</a>
                </div>

                <div class="alert alert-dark" id="comment">
                    <h2 class="alert-heading">Votre avis compte !</h2>
                    {% if date() > date(booking.endDate) %}
                        {% set comment = booking.ad.commentFromAuthor(app.user) %}
                        {% if comment is not null %}
                            <blockquote>
                                {{ comment.content }}
                            </blockquote>

                            <strong>Note : {% include 'partials/rating.html.twig' with {'rating' : comment.rating } %}</strong>
                        {% else %}
                            {{ form_start(form) }}
                            {{ form_widget(form) }}
                            <button type="submit" class="btn btn-success">Confirmer !</button>
                            {{ form_end(form) }}
                        {% endif %}
                    {% else %}
                        <p>Vous ne pourrez pas noter cette annonce tant que 
                        votre voyage ne sera pas complet !</p>
                    {% endif %}
                </div>

            </div>
            <div class="col">
                <div class="alert alert-dark">
                    <h2 class="alert-heading">Votre hébergement</h2>

                    <h4>
                        <a href="{{ path('ads_show', {'slug': ad.slug }) }}">{{ ad.title }}</a>
                    </h4>

                    <img src="{{ad.coverImage}}" alt="Image de {{ ad.title }}" class="img-fluid">

                    {{ ad.content | raw }}

                    <a href="{{ path('ads_show', {'slug' : ad.slug }) }}" class="btn btn-primary">Plus d'infos</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}