src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *  fields={"email"},
 *  message="Un autre utilisateur s'est déjà inscrit avec cette adresse mail, merci de la modifier"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre prénom")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre nom de famille")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message = "Veuillez donner une URL valide pour votre avatar !")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(
     *      propertyPath="hash", 
     *      message="Vous n'avez pas correctement confirmé votre mot de passe")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 10,
     *      minMessage = "Votre introduction doit faire au moins 10 caractères"
     * )
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(
     *      min = 100,
     *      minMessage = "Votre description doit faire au moins 100 caractères"
     * )
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    public function getFullName() {
        return "{$this->firstName} {$this->lastName}";
    }

    /**
     * Initilizes the slug before persist or before update
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initializeSlug() {
        if(empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles() {

        $roles = $this->userRoles->map(function($role) {
            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function getPassword() {
        return $this->hash;
    }

    public function getSalt() {}

    public function getUsername() {
        return $this->email;
    }

    public function eraseCredentials() {
        
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use App\Form\ImageType;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class AdType extends ApplicationType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'title',
                TextType::class,
                $this->getConfiguration(
                    "Titre",
                    "Tapez un super titre pour votre annonce"
                ))
            ->add(
                'slug', 
                TextType::class, 
                $this->getConfiguration(
                "Adresse Web",
                "Tapez l'adresse web (automatique)", 
                [
                    'required' => false
                ]
            ))
            ->add(
                'coverImage', 
                UrlType::class, 
                $this->getConfiguration(
                "URL de l'image principale",
                "Donnez l'adresse d'une image qui donne vraiment envie"
            ))
            ->add(
                'introduction', 
                TextType::class, 
                $this->getConfiguration(
                "Introduction",
                "Donnez une description globale de l'annonce"
            ))
            ->add(
                'content', 
                TextareaType::class, 
                $this->getConfiguration(
                "Description détaillée",
                "Tapez une description qui donne vraiment envir de venir chez vous"
            ))
            ->add(
                'rooms', 
                IntegerType::class, 
                $this->getConfiguration(
                "Nombre de chambres",
                "Le nombre de chambres disponibles"
            ))
            ->add(
                'price', 
                MoneyType::class, 
                $this->getConfiguration(
                "Prix par nuit",
                "Indiquez le prix que vous voulez pour une nuit"
            ))
            ->add(
                'images', 
                CollectionType::class,
                [
                    'entry_type' => ImageType::class,
                    'allow_add' => true,
                    'allow_delete' => true
                ]
            );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Form\AdType;
use App\Entity\Image;
use App\Repository\AdRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdController extends AbstractController
{
    /**
     * @Route("/ads", name="ads_index")
     */
    public function index(AdRepository $repo)
    {
        $ads = $repo->findAll();

        return $this->render('ad/index.html.twig', [
            'ads' => $ads
        ]);
    }
    
    /**
     * Allow user to create an Ad
     * 
     * @Route("/ads/new", name="ads_create")
     * @IsGranted("ROLE_USER")
     * 
     * @return Response
     */
    public function create(Request $request, EntityManagerInterface $manager) {
        $ad = new Ad();

        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            foreach($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }

            $ad->setAuthor($this->getUser());
            
            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "L'annonce <stong>{$ad->getTitle()}</strong> a bien été enregistrée!"
            );

            return $this->redirectToRoute("ads_show", [
                'slug' => $ad->getSlug()
            ]);
        }
        
        return $this->render("ad/new.html.twig", [
            'form' => $form->createView()
        ]);
    }

    /**
     * Update an existing Ad
     * 
     * @Route("/ads/{slug}/edit", name="ads_edit")
     * @Security(
     *      "is_granted('ROLE_USER') and user === ad.getAuthor()",
     *      message = "Vous n'êtes pas autorisé à modifier cette annonce"
     * )
     *
     * @return Reponse
     */
    public function edit(Request $request, Ad $ad, EntityManagerInterface $manager) {

        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            foreach($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }
            
            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "Les modifications de l'annonce <stong>{$ad->getTitle()}</strong> ont bien été enregistrées!"
            );

            return $this->redirectToRoute("ads_show", [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/edit.html.twig', [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }

    /**
     * Display a single Ad
     * 
     * @Route("/ads/{slug}", name="ads_show")
     * 
     * @return Response
     */
    public function show(Ad $ad) {
        // Gets the Ad based on the slug
        return $this->render('ad/show.html.twig', [
            'ad' => $ad
        ]);
    }

    /**
     * Allow user to delete an Ad
     * 
     * @Route("/ads/{slug}/delete", name="ads_delete")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Vous n'avez pas le droit d'accéder à cette ressource") 
     *
     * @param Ad $ad
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function delete(Ad $ad, EntityManagerInterface $manager) {
        $manager->remove($ad);
        $manager->flush();

        $this->addFlash(
            "success",
            "L'annonce <strong>{$ad->getTitle()}</strong> a bien été supprimée"
        );

        return $this->redirectToRoute("ads_index");
    }

}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug': ad.slug }) %}
<div class="col-md-4">
    <div class="card bg-light mb-3">
        <div class="card-header text-center">
            {{ ad.rooms }} chambres, <strong><b>{{ ad.price | number_format(2, ',', ' ') }}&#8364; / nuit</b></strong> <br>
            {% if ad.comments |length > 0 %}
                {% include 'partials/rating.html.twig' with {'rating': ad.getAvgRatings } %}
            {% else %}
                <small>Pas encore noté</small>
            {% endif %}
        </div>
        <a href="{{ url }}">
            <img src="{{ ad.coverImage }}" alt="Image de l'appartement"
            style="height: 200px; width: 100%; display:block">
        </a>
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ url }}">
                    {{ ad.title }}
                </a>
            </h4>
            <p class="card-text">
                {{ ad.introduction }}
            </p>
            <a href="{{ url }}" 
            class="btn btn-primary float-right">En savoir plus</a>
            {% if app.user and app.user == ad.author %}
                <a href="{{ path('ads_edit', {'slug': ad.slug }) }}" class="btn btn-primary mt-2">Editer l'annonce</a>
            {% endif %}
        </div>
    </div>
</div>

templates/ad/_collection.html.twig
{% block _ad_images_widget %}
    <p>Ici, vous pouvez ajouter vos propres images !</p>

    {{ form_widget(form) }}
 
    <input type="hidden" id="widgets-counter" value="0">

    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">
            <i class="fas fa-plus"></i>
            Ajouter une image
        </button>
    </div>
{% endblock %}

{% block _ad_images_entry_row %}
    {{ form_widget(form)}}
{% endblock %}


{# The sub form based on an Ad specific field 
    (images - CollectionType) in this case #}

{% block _ad_images_entry_widget %}
    <div class="form-group" id="block_{{id}}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url)}}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption)}}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
            </div>
        </div>
        
    </div>
{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition d'une annonce{% endblock %}

{# Allows Twig to use a custom form. _self means the current page #}
{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}

    <div class="container">
        <h1>Modifier l'annonce : {{ad.title}}</h1>

        {{ form_start(form) }}

        {{ form_widget(form )}}

        <button type="submit" class="btn btn-primary">Editer nouvelle annonce</button>

        {{ form_end(form) }}
    </div>

{% endblock %}

{# Javascript part that handles the sub form logic. #}

{% block javascripts %}

<script src="/js/ad.js"></script>

{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces !{% endblock %}

{% block body %}
<div class="container">
    <h1 class="my-5">Voici nos annonces de nos hôtes !</h1>

    <div class="row">
        {% for ad in ads %}
            {% include 'ad/_ad.html.twig' %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/ad/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Création d'une annonce
{% endblock %}

{# Allows Twig to use a custom form. _self means the current page #}
{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}

    <div class="container">
        <h1 class="my-5">Créer une nouvelle annonce</h1>
        {{ form_start(form) }}

        <div class="row">
            <div class="col">
                <div class="alert alert-dark">
                    <h2>Informations générales</h2>
                    <hr>
                    {{ form_row(form.title) }}
                    {{ form_row(form.slug) }}
                    {{ form_row(form.price) }}
                    {{ form_row(form.rooms) }}
                </div>
                <div class="alert alert-dark">
                    <h2>Détails de l'annonce</h2>
                    <hr>
                    {{ form_row(form.introduction) }}
                    {{ form_row(form.content) }}
                </div>
            </div>
            <div class="col">
                <div class="alert alert-dark">
                    <h2>Images de l'annonce</h2>
                    <hr>
                    {{ form_row(form.coverImage) }}
                    {{ form_row(form.images) }}
                </div>
            </div>
        </div>

        <div class="alert alert-success clearfix">
            <h2 class="alert-heading">Sauvegarder mon annonce</h2>
            <p>Vous êtes sur le point de créer votre annonce</p>
            <button type="submit" class="btn btn-primary float-right">
                <i class="fas fa-check"></i>
                Créer la nouvelle annonce
            </button>
        </div>

        {{ form_end(form) }}
    </div>

{% endblock %}

{# Javascript part that handles the sub form logic. #}

{% block javascripts %}

<script src="/js/ad.js"></script>

{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ ad.title }}
{% endblock %}

{% block body %}
<div class="Ad-title" style="background-image: url({{ ad.coverImage }})">
    <div class="container">
        <h1>{{ ad.title }}</h1>
        <p>{{ ad.introduction }}</p>
        <p class="h2">
            <strong>{{ ad.rooms }} chambres</strong> pour
            <strong>{{ ad.price | number_format(2, ',', ' ') }} euros</strong> par nuit
        </p>
        <a href="{{ path("booking_create", {'slug' : ad.slug }) }}" class="btn btn-primary">Réserver !</a>
        {% if app.user and app.user == ad.author %}
            <a href="{{ path('ads_edit', {'slug': ad.slug }) }}" class="btn btn-secondary">Modifier l'annonce</a>

            <a href="{{ path('ads_delete', {'slug': ad.slug }) }}" class="btn btn-primary mt-2"
                onClick="return confirm(`Êtes vous sur de vouloir supprimer l'annonce : {{ ad.title }} ?`)">Supprimer l'annonce</a>
        {% endif %}
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-8 mb-3">
            {{ ad.content | raw }}
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for image in ad.images %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{loop.index0}}" 
                        {% if loop.first %}class="active" {% endif %}></li>
                    {% endfor %}
                </ol>
                <div class="carousel-inner">
                    {% for image in ad.images %}
                        <div class="carousel-item {% if loop.first %} active {% endif %}">
                            <img src="{{image.url}}" class="d-block w-100" alt="...">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>{{ ad.title }}</h5>
                                <p>{{ image.caption }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <hr>

            {% if ad.comments|length > 0 %}
                <h2 class="mb-3">Commentaires de nos voyageurs :</h2>
                
                <div class="alert alert-info">
                    <h4 class="alert-heading text-center">
                        <div class="row align-items-center">
                            <div class="col">
                                Note globale donnée par nos voyageurs
                            </div>
                            <div class="col">
                                {% include 'partials/rating.html.twig' with {'rating': ad.getAvgRatings } %}
                                <br>
                                <small>(Calculée sur {{ ad.comments|length }} avis)</small>
                            </div>
                        </div>
                    </h4>
                </div>

                {% for comment in ad.comments %}
                    <div class="bg-light rounded mb-3 py-3 px-3">
                        <strong>{{ comment.author.firstName }}</strong> a dit :
                        <blockquote>
                            {{ comment.content }}
                        </blockquote>
                        <strong>Note donnée : </strong>
                        {% set rating = comment.rating %}
                        {% include 'partials/rating.html.twig' with {'rating': comment.rating } %}
                    </div>
                {% endfor %}
            {% else %}
                <h2>Cette annonce n'a pas encore reçu de commentaires ...</h2>
            {% endif %}
        </div>
        <div class="col">
            {% set a = ad.author %}
            <div class="row mb-3 align-items-center">
                <div class="col-3">
                    <a href="{{ path('user_show', {'slug': a.slug }) }}"><img src="{{a.picture}}" class="avatar avatar-medium" alt="Avatar de {{a.fullName}}"></a>
                </div>
                <div class="col">
                    <a href="{{ path('user_show', {'slug': a.slug }) }}">
                        <h3>{{a.fullName}}</h3>
                    </a>
                    <span class="badge badge-primary">{{a.ads | length }} annonces</span>
                </div>
            </div>
            {{ a.description | raw }}
        </div>
    </div>
</div>
{% endblock %}